/*

 BGMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 32 x 18
   Tile set      : bgtiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 64
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __bgmap_h_INCLUDE
#define __bgmap_h_INCLUDE

#define bgmapWidth 32
#define bgmapHeight 18
#define bgmapBank 0

extern const unsigned char bgmap[];

#endif

/* End of BGMAP.H */
