/*

 KEYBOARDMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : E:\Source\Repos\TouhouGBA\gb\learn\fonts.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __keyboardmap_h_INCLUDE
#define __keyboardmap_h_INCLUDE

#define keyboardmapWidth 20
#define keyboardmapHeight 18
#define keyboardmapBank 0

extern const unsigned char keyboardmap[];

#endif

/* End of KEYBOARDMAP.H */
